# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            '<img src="https://avatars2.githubusercontent.com/u/5483556?v=3&s=460"></img>'
tagline:          ''
description:      'Anshzinc'
url:              http://anshole.github.io
baseurl:          /

author:
  name:           '_'
  url:            https://twitter.com/

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/anshole/anshole.github.io
