# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Anshzinc
tagline:          ''
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://anshole.github.io
baseurl:          /

author:
  name:           '_'
  url:            https://twitter.com/

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/anshole/anshole.github.io
